import { GuestLayout } from '@components/layouts/guest-layout';
import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <GuestLayout>
        <button className="btn btn-primary">Hello</button>
      </GuestLayout>
    </>
  );
};

export default Home;
