import Layout from '@components/layouts/layout';
import { useAppSelector } from '@redux/store/hooks';
import type { NextPage } from 'next';
import Head from 'next/head';
import Login from './login';

const Home: NextPage = () => {
  const { user } = useAppSelector((state) => state.auth);

  // if (!user || user.isLoggedIn === false) {
  //   return <Login />;
  // }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <button className="btn btn-primary">Hello</button>
      </Layout>
    </>
  );
};

export default Home;
