import Loader from '@components/loader';
import Head from 'next/head';
import { ReactNode } from 'react';

const GuestLayout = ({ children }: { children: ReactNode }) => {
  return (
    <>
      <Head>
        <title>Login | Vocal Admin Management</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {children}

      <Loader />
    </>
  );
};

export default GuestLayout;
