import Header from '@components/common/header';
import Sidebar from '@components/common/sidebar';
import { authSelector } from '@redux/selectors';
import { useAppSelector } from '@redux/store/hooks';
import dynamic from 'next/dynamic';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { ReactNode, useEffect } from 'react';

const TopProgressBar = dynamic(
  () => {
    return import('@components/top-progress-bar');
  },
  { ssr: false }
);

const Layout = ({ children }: { children: ReactNode }) => {
  const router = useRouter();
  const { user: currentUser } = useAppSelector(authSelector);

  useEffect(() => {
    if (!currentUser) {
      router.push({
        pathname: '/login',
        query: { from: router.asPath },
      });
    }
  }, [currentUser, router]);

  return (
    <>
      <Head>
        <title>Vocal Admin Management</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex h-screen drawer">
        <Sidebar />
        <div className="flex flex-col flex-1 overflow-auto w-[1640px] drawer-content">
          <Header />
          <main className="w-[1640px]">{children}</main>
        </div>
      </div>

      <TopProgressBar />
    </>
  );
};

export default Layout;
